endpoints.health.enabled: true

hazelcast.max.no.heartbeat.seconds: 6

admin.application.url: http://216.218.200.224:30053/admin/companies

news.application.url: http://216.218.200.224:30056/news/twitter
